language: python
sudo: required
python:
    - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install puppet
  - sudo puppet apply puppet/site.pp
  - sudo pip list show


script: python unittests/test_module.py